//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QRMenu2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qrmenuEntities : DbContext
    {
        public qrmenuEntities()
            : base("name=qrmenuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kategori> kategori { get; set; }
        public DbSet<urunler> urunler { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<yumurta> yumurta { get; set; }
    }
}
